### PR TITLE
replacing exec call with runpy.run_path

### PR DESCRIPTION
**Pull request by asmodehn**

### CODE REVIEW

**Comment by asmodehn** [comment]
Fixing https://github.com/ros/catkin/issues/872

**Comment by dirk-thomas** [comment]
I am sorry for the late reply. The patch looks great. I didn't know about `runpy`. This is much cleaner. Thanks.

**Comment by asmodehn** [comment]
Looks like we need to do the same on interrogate_setup_dot_py : 
http://build.ros.org/job/Kpr__genmsg__ubuntu_xenial_amd64/8/consoleFull

**Comment by asmodehn** [comment]
Ah no maybe it s just that this version didn't make it on the build farm yet... I ll wait a bit more.

**Comment by dirk-thomas** [comment]
`genmsg` will only use released versions of `catkin`. So the `genmsg` PR job will only pass once a new version of `catkin` has been released with this patch.

**Pull request merged**
