### PR TITLE
fix problem when cm / cmi is invoked in a symlinked folder

### PR DESCRIPTION
**Pull request by dirk-thomas**
@tfoote @wjwwood Please review.

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by tkruse** [comment]
Obviously, this issue does not only affect the `-C` argument, but all of:
`catkin_make --build ... --source ... -DCATKIN_DEVEL_PREFIX ... -DCMAKE_INSTALL_PREFIX= ...`
The same arguments where you found this defect in #603

Also I do not understand why this patch does not include a fallback to os.getcwd() for shells not supporting os.getenv('PWD'), as I had explained in the code comment in #638. I have not tried, but this change may simply break on Windows because of that.

Also I would recommend refactoring the codebase such that catkin_make and catkin_make_isolated use the same functions to do the same things, unless you consider code duplication a good practice. I had also already done this in #603 until you asked me to create a separate PR for that, so maybe you prefer to take the time to implement this yourself, or maintain duplicate code.

**Comment by dirk-thomas** [comment]
Can you please describe how you expect the following line of the patch to fail on Windows?

```
os.getenv('PWD', '.')
```

**Comment by tkruse** [comment]
I don't know. Possibly it will work. I would use os.getcwd().

**Comment by wjwwood** [comment]
You could invoke `cd` on Windows: http://stackoverflow.com/questions/921741/windows-equivalent-to-unix-pwd

> Also I would recommend refactoring the codebase such that catkin_make and catkin_make_isolated use the same functions to do the same things, unless you consider code duplication a good practice. I had also already done this in #603 until you asked me to create a separate PR for that, so maybe you prefer to take the time to implement this yourself, or maintain duplicate code.

Please, quit being provocative. "I would recommend refactoring ... to prevent code duplication, like I had in #603 before." would have been sufficient.

**Comment by tkruse** [comment]
Do you need a new github issue for the same problem occurring for
``catkin_make --build ... --source ... -DCATKIN_DEVEL_PREFIX ... -DCMAKE_INSTALL_PREFIX= ...`, or would you maybe reconsider reopening #638?

I am not provocative, I am reporting facts that make me angry. It is not sufficient to be factual, if the problem that needs to be solved extends to OSRF's communication policies. If you think that #603 was handled for the best of the ROS community, say so. If not, who is taking responsibility for it?

**Comment by tfoote** [comment]
@tkruse Please take a look at the fix proposed in #642 

Venting about unrelated topics in issues is not appropriate and is often provocative. Please avoid writing emails and messages while angry as it is not conducive to an open and productive conversation.

**Comment by tfoote** [comment]
Note: '.' will work on POSIX and Windows: https://docs.python.org/2/library/os.html#os.curdir

**Comment by tkruse** [comment]
#642 seems ok

@wjwwood attempted to judge and lecture me here in public. I agree with @tfoote such an action by @wjwwood are not appropriate and often provocative. Just look at where that got you.

Consider taking your own advices more seriously yourselves.

If you feel like you have violated your own code of what is appropriate here and what not, consider taking responsibility.

Also, when you are done lecturing me about how I should communicate, maybe take the time to actually read up on that topic:
- http://hear.ceoblognation.com/2013/02/25/tips-for-dealing-with-the-bad-and-ugly-of-customer-feedback-from-entrepreneurs-and-business-owners/
- http://www.searchenginejournal.com/how-not-to-respond-to-negative-reviews-online-aka-how-to-make-people-hate-your-brand/59903/
- http://mashable.com/2010/02/21/deal-with-negative-feedback/

Feel free to try and respond to my initial feedback in accordance to what professionals suggest. It's a valuable excercise.

**Comment by dirk-thomas** [comment]
@tkruse On repositories which I maintain I will remove any further posts from you (or others) with content which is not strictly on topic (e.g. like your previous comment with these links) or any personally insulting content (as in recent other tickets) since they do harm the ROS ecosystem.

Any person working on an open source project should watch this https://www.youtube.com/watch?v=Q52kFL8zVoM and remember it when interacting with the community.

No further comments will be accepted on this ticket (except of course when being about the pull request itself).

**Comment by dirk-thomas** [comment]
Since I am not aware of any use case which would not work with the proposed patch (even on Windows) I won't take any further actions on this already merged pull request. If there are cases not yet covered please comment with a detailed description of the scenario and a reproducible command sequence.

**Pull request merged**
