### PR TITLE
add skipped / disabled tests to catkin_test_results summary

### PR DESCRIPTION
**Pull request by dirk-thomas**
Replaces #840.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@ros/ros_team Please review.

**Review by wjwwood — APPROVED** [review]
lgtm

**Comment by rsinnet** [comment]
@dirk-thomas Thanks for dealing with the interface compatibility issue. I hadn't thought of the interface as a public interface but that's a very good point. I did a quick smoke test and it seems fine. The changes look good as well.

**Comment by dirk-thomas** [comment]
Thanks.

**Pull request merged**
