### PR TITLE
Use atomic APPEND write mode for writing source spaces to .catkin marker file

### LINKED ISSUE #670: ".catkin" marker file can be overwritten if two catkin instances are running with a shared develspace
For example, when using `catkin build` from [catkin_tools](http://github.com/catkin/catkin_tools), there is a chance that some package source directories will not be listed in the `.catkin` file. If one package A writes it after another package B has read it, but before B has written to it, then A's modifications will be overwritten when B writes to it. This, in turn, means that they will not enter into `$ROS_PACKAGE_PATH`.

This was formerly discovered and discussed in catkin/catkin_tools#77.

### PR DESCRIPTION
**Pull request by jbohren**
Same as #671 but fixes #670 for groovy/hydro.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I am closing this since any change going to the _groovy-devel_ branch will be cherry-picked from the _indigo-devel_ branch whenever possible.

**Comment by jbohren** [comment]
Sounds good.

**Comment by jbohren** [comment]
> I am closing this since any change going to the groovy-devel branch will be cherry-picked from the indigo-devel branch whenever possible.

This never got cherry-picked, and people are running into issues with it using `catkin build`, any chance it could get pulled into groovy/hydro?

**Comment by dirk-thomas** [comment]
It looks to me the patch has been cherry-picked to the _groovy-devel_ branch in https://github.com/ros/catkin/commit/f23396d11e6d459937ebfaf68eba47832bcf9f6f.

Also new version of catkin (0.5.89) has been released into _Groovy_ and _Hydro_ since then.

**Pull request closed without merging**
