### PR TITLE
fix unicode error with japanese LANG (fix #578)

### PR DESCRIPTION
**Pull request by dirk-thomas**
@josegaert @nicolasWDC @saljam @wjwwood @yukota This PR supersedes #578.

Please test your use case against this branch of catkin and report if it works for you. If not please provide a detailed description how to reproduce your problem.

### CODE REVIEW

**Comment by saljam** [comment]
ok, this does the job.

**Comment by nicolasWDC** [comment]
Ok for me !

**Comment by yukota** [comment]
Looks good to me! Thank you!

**Comment by wjwwood** [comment]
+1 works on my machine too.

**Comment by josegaert** [comment]
Did the job, Tx

**Pull request merged**
