### PR TITLE
updated PYTHON_INSTALL_DIR generation

### PR DESCRIPTION
**Pull request by wyc**
In response to #632 #635

This patch uses Python to report PYTHON_INSTALL_DIR, and it therefore allows cmake/python.cmake and python/catkin/builder.py to share most of the same code. It eliminates the debian-specific directive and works with python2 and python3. It has been tested on Gentoo, Debian, and Windows.

More testing is in order to confirm its complete functionality.

### CODE REVIEW

**Comment by wyc** [comment]
unfortunately the Travis CI build seems to fail due to a shortcoming of python's virtualenv:
https://github.com/pypa/virtualenv/issues/228

**Comment by wyc** [comment]
looks like Travis CI was okay with that one. requesting human review now.

**Comment by wjwwood** [comment]
Thanks for the pull request. As you can probably imagine, we'll have to scrutinize this one pretty hard since it affects all Python packages in ROS.

I'll give some feedback soon.

**Comment by smits** [comment]
I can confirm that the provided patch fixes #635. Thanks!!

**Comment by spaghetti-** [comment]
I would like to mention that this patch did not work for me on gentoo

`Portage 2.2.28 (python 2.7.10-final-0, default/linux/amd64/13.0, gcc-5.4.0, glibc-2.22-r4, 4.4.26-gentoo x86_64)` on kinetic (manual patch)

**Comment by dirk-thomas** [comment]
@spaghetti- Can you please also try the follow up PR #831. And if it doesn't work provide some more information what the problem is, what the various paths are in your case in order to allow iterating on the patch.

**Comment by spaghetti-** [comment]
Yes of course. However @dirk-thomas is the right approach having `lib`/`lib64` both? On my OS X install I only have `lib`.

**Comment by dirk-thomas** [comment]
There can't be more than one location for a single package. Should it needs to be all in either `lib` or `lib64`. Each package can pick a different location though as long the Python path is set to include that path.

**Comment by dirk-thomas** [comment]
I will close this as a duplicate of #831. Please continue the discussion there.

**Pull request closed without merging**
