### PR TITLE
Use DYLD_FALLBACK_LIBRARY_PATH to not interfere with system libraries on OS X.

### PR DESCRIPTION
**Pull request by kyonifer**
I'm currently working on creating a set of Portfiles to get ROS properly supporting within macports (https://github.com/kyonifer/ros-macports). One issue i've run into is that ROS uses DYLD_LIBRARY_PATH to find libs at runtime. In general, this approach causes issues with DYLD_ libraries overriding builtin libraries. For example, once a user has sourced setup.bash, macport's libjpeg overrides the system libJPEG which export different symbols. This makes it impossible to run e.g. Sublime Text or rqt:

```
kyons-MacBook-Pro:~ kyon$ source setup.bash
kyons-MacBook-Pro:~ kyon$ sl
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /opt/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Trace/BPT trap: 5
kyons-MacBook-Pro:~ kyon$ 
kyons-MacBook-Pro:~ kyon$ rqt
Traceback (most recent call last):
  File "/opt/local/bin/rqt", line 16, in <module>
    sys.exit(main.main())
  File "/opt/local/lib/python2.7/site-packages/rqt_gui/main.py", line 56, in main
    return super(Main, self).main(argv, standalone=standalone, plugin_argument_provider=plugin_argument_provider)
  File "/opt/local/lib/python2.7/site-packages/qt_gui/main.py", line 326, in main
    from python_qt_binding import QT_BINDING
  File "/opt/local/lib/python2.7/site-packages/python_qt_binding/__init__.py", line 45, in <module>
    from .binding_helper import loadUi, QT_BINDING, QT_BINDING_MODULES, QT_BINDING_VERSION  # @UnusedImport
  File "/opt/local/lib/python2.7/site-packages/python_qt_binding/binding_helper.py", line 258, in <module>
    _select_qt_binding(getattr(sys, 'SELECT_QT_BINDING', None))
  File "/opt/local/lib/python2.7/site-packages/python_qt_binding/binding_helper.py", line 84, in _select_qt_binding
    raise ImportError('Could not find Qt binding (looked for "%s"):\n%s' % (DEFAULT_BINDING_ORDER, '\n'.join(error_msgs)))
ImportError: Could not find Qt binding (looked for "['pyqt', 'pyside']"):
  ImportError for "pyqt": dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyQt4/QtCore.so, 2): Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /opt/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  ImportError for "pyside": No module named PySide.QtCore
```

Theres two solutions to this: 
- Ask libraries to use install names with full paths (or rpaths) encoded, thereby eliminating libs from being on the path at all. 
- Use DYLD_FALLBACK_LIBRARY_PATH, as dyld will only search the fallback path once it exhausts the builtin paths (eliminating interference with links that were previously working). 

The latter is easily changed as seen in the attached pull request. The former is done by passing flags to catkin_make while building catkin and then eliminating DYLD_ vars from the setup.bash altogether. See the ros-desktop Portfile in the above repository for an example.

I've done both for macports, but it'd be good to change things upstream one way or the other.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Since I don't know what the "right" way on OS X is I will add @wjwwood.

One thing regarding the pull request: it only replaces one location there the environment variable is used and is therefore _incomplete_. But before updating it lets wait until we figured out what the way to go is.

**Comment by wjwwood** [comment]
Using the `DYLD_FALLBACK_` environment variable will be the simplest solution, but I have always wanted to remove `DYLD_` variables all together.  The preferred way to do this on OS X is to use correct `rpath`'s for everything. I am almost certain that removing these variables will break somethings in the current ROS ecosystem on OS X, but in reality they should be fixed.

A path forward might be to use the `DYLD_FALLBACK_` variable for now, and later drop it once someone can make sure that desktop(-full) can build AND run without it.

**Comment by dirk-thomas** [comment]
If we would switch from `DYLD_LIBRARY_PATH` to `DYLD_FALLBACK_LIBRARY_PATH` would there be any regression? Or would it for now just fix the above mentioned issues?

Would that also imply that system libraries would always take precedence over the ones from ROS packages? Imo this would be bad since the ROS libraries will not overlay the system libraries as it is intended and done on all other platforms.

**Comment by kyonifer** [comment]
Indeed the preferred way is to code the install names with rpaths or even fully qualified paths. This is done during the config/make/install process, depending on how you pass cmake flags. I've managed to encod working install names successfully with all but 3 of the libs in groovy desktop-full with the following invocation:

```
     exec ${worksrcpath}/src/catkin/bin/catkin_make_isolated \
          --source ${worksrcpath}/src \
          --build ${worksrcpath}/build_isolated \
          --devel ${worksrcpath}/devel_isolated \
          -DCMAKE_SKIP_RPATH:BOOL=OFF \
          -DCMAKE_INSTALL_NAME_DIR:STRING=${prefix}/lib \
          -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON \
          -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON \
          -DSETUPTOOLS_DEB_LAYOUT=OFF \
          -DPYTHON_EXECUTABLE:FILEPATH=${prefix}/bin/python2.7
```

With this done, removing DYLD_\* completely doesnt do anything to break ROS on the surface (I haven't done any extensive testing though). Another option is for me to just remove DYLD_ vars from the setup.bash on macports only, since its working without these environment variables set as of now.

**Comment by dirk-thomas** [comment]
Since this patch has some undesired side effects and it is not clear how a better solution would look like I would close this issue and mark it as "wontfix". Or are there any further reasons to keep this open?

**Comment by kyonifer** [comment]
What are the undesired side effects with using DYLD_FALLBACK_LIBRARY_PATH? We've been using it with a downstream patch in macports successfully, I'm not aware of anything that is worse for having done so. It seems to be better in all cases than using DYLD_LIBRARY_PATH as it is written now. Both of those options are worse than removing the env vars completely (which might break things).

**Comment by wjwwood** [comment]
I would agree that we cannot use the fallback path because that would not allow you to overlay libraries which are in the system normal library path (`/usr/local/lib`) on mac. The problem arising here is that MacPorts does not want to expose `libjpeg`, so it explicitly avoids putting `/opt/local/lib` into the `DYLD_LIBRARY_PATH`, but once you install ROS packages there (which apparently do not have proper run paths setup), you need that folder to be on the path.

As I see it, there are two solutions for MacPorts:
- Use CMake CLI options to setup RPath's correctly and remove prefixing of `DYLD_LIBRARY_PATH` from only the setup file in `/opt/local/lib`.
- Modify only the setup file in `/opt/local/lib` to use `DYLD_FALLBACK_LIBRARY_PATH` in stead of `LD_LIBRARY_PATH`

> What are the undesired side effects with using DYLD_FALLBACK_LIBRARY_PATH?

I think what he is talking about is that if you install some ROS packages to `/usr/local` (for example), then those libraries there can never be overlaid with libraries on the `DYLD_FALLBACK_LIBRARY_PATH`.

**Comment by kyonifer** [comment]
> I think what he is talking about is that if you install some ROS packages to /usr/local (for example), then those libraries there can never be overlaid with libraries on the DYLD_FALLBACK_LIBRARY_PATH.

Ah okay.

I've went down the RPath route before and got stuck on something (this was long enough ago I don't recall what broke exactly)-- in theory it should work though. It might be worth trying again and see if a problem still exists with the latest master. Option #2 seems like the easiest fix; in fact, thats what I was trying to do with my PR, but I'm guessing that template probably gets copied elsewhere too.

Another option is to just close this issue and leave it as a patch in ros-macports, but that will lead to divergent behavior between homebrew and macports w.r.t. overlaying libraries as you mentioned.

**Comment by wjwwood** [comment]
Well, this isn't generally a problem with Homebrew because things which affect the system (like newer versions of `libjpeg`) are not put into `/usr/local/lib`, instead they are left in their Cellar and the appropriate `-I` and `-L` flags are passed to dependent formulae, such that they are made available for whom ever needs them, but never pollute the system library path.

**Comment by kyonifer** [comment]
/opt/local/lib is not a system path, so I'd see putting it on the DYLD_\* path equivalent to exposing cellar directories to the DYLD_\* path (the former is what catkin does currently on macports). Really the solution is to remove dependency on environment variables and not expose the /opt/local/lib to the system. However, in the meantime fallback is a decent compromise.

Leaving it as is and wontfix'ing this issue will lead to divergence though-- homebrew versions will allow overlaying and macports wont (since this PR is currently patched in during macports install).

**Comment by wjwwood** [comment]
If you don't mess with the RPath's and just set `DYLD_FALLBACK_LIBRARY_PATH` for _only_ the setup file in `/opt/local/lib`, then I think everything is fine (no divergence).

**Comment by kyonifer** [comment]
Yeah I think that's the best option. Should I just replace the file during destroot (macports portfile) or is that an easy fix to change in catkin? If doing so (changing only prefix/lib setup to be FALLBACK) won't hurt homebrew, I'd prefer to have the fix in catkin since it's one less patch to maintain, but either way works.

**Comment by dirk-thomas** [comment]
@kyonifer Since we can't change the environment variable in general and the install prefix `/opt/local/lib` is not a reliable indicator for catkin to use a different environment variable I would recommend you to patch this after pull the catkin upstream version.

Since you mentioned before that this is acceptable for you (even if it requires maintaining a local patch for it) I will mark this ticket as closed. Please feel free to continue commenting on it.

**Comment by LiohAu** [comment]
Now that OSX 10.11 forbid the DYLD_FALLBACK_LIBRARY_PATH and DYLD_LIBRARY_PATH env vars the only way, if I correctly understand, is to configure appropriatelly the install names right ? 
If so, are there any plans on this (will this issue be re-opened for instance) ?

PS : I hope it wasn't a mistake to post on that closed issue.

**Comment by dirk-thomas** [comment]
@wjwwood Can you comment on this and what is necessary for OS X 10.11?

**Comment by wjwwood** [comment]
`DYLD_FALLBACK_LIBRARY_PATH` doesn't address the issue.

The issue is that no (or almost no) `DYLD_*` environment variables will persist through an invocation of the shell. That includes sourcing. So we have to deliver, at least on os x, binaries which have the correct rpath's such that setting a library path environment variable is not necessary to run. Unfortunately that includes our dependencies and not just our shared libraries.

I'm not sure about the solution, but I did test this patch which seems to have worked for a lot of cases:

``` diff
diff --git a/cmake/catkinConfig.cmake.in b/cmake/catkinConfig.cmake.in
index 8afb6df..a8d4ab8 100644
--- a/cmake/catkinConfig.cmake.in
+++ b/cmake/catkinConfig.cmake.in
@@ -10,6 +10,32 @@
 # :outvar <comp>_INCLUDE_DIRS/_LIBRARY_DIRS/_LIBRARY:
 #    contains the include dirs / library dirs / libraries of the searched component <comp>.

+macro(_set_cmake_policy_to_new_if_available policy)
+  if(POLICY ${policy})
+    cmake_policy(SET ${policy} NEW)
+  endif()
+endmacro()
+_set_cmake_policy_to_new_if_available(CMP0042)
+set(CMAKE_MACOSX_RPATH TRUE)
+# use, i.e. don't skip the full RPATH for the build tree
+SET(CMAKE_SKIP_BUILD_RPATH  FALSE)
+
+# when building, don't use the install RPATH already
+# (but later on when installing)
+SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
+
+SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
+
+# add the automatically determined parts of the RPATH
+# which point to directories outside the build tree to the install RPATH
+SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
+
+# the RPATH to be used when installing, but only if it's not a system directory
+LIST(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/lib" isSystemDir)
+IF("${isSystemDir}" STREQUAL "-1")
+   SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
+ENDIF("${isSystemDir}" STREQUAL "-1")
+
 if(CATKIN_TOPLEVEL_FIND_PACKAGE OR NOT CATKIN_TOPLEVEL)
   set(catkin_EXTRAS_DIR "@PKG_CMAKE_DIR@")

```

I think this would need to be refined and narrowed in scope. It's based on a recommendation here: https://cmake.org/Wiki/CMake_RPATH_handling#Always_full_RPATH

**Comment by dirk-thomas** [comment]
Can one of you please create a pull request which implements the proposed logic only for OS X. Thank you.

**Comment by LiohAu** [comment]
@wjwwood your fix would solve the problem for any package built using catkin ? 

Right now I have encountered the issue with a gazebo plugin. The libgazebo_ros_paths_plugin.dylib and libgazebo_ros_api_plugin.dylib plugins are loaded in gazebo by dlopen() calls and the loading fails because the libraries referenced by these 2 plugin/libraries (libroslib.dylib, libtf2_ros.dylib, libtf.dylib and a dozen more...) are in /opt/ros/indigo/lib/.

I assume that if I had not built the libgazebo_ros_api_plugin.dylib/libgazebo_ros_paths_plugin.dylib myself in my workspace, they would also be in /opt/ros/indigo and the loading would probably succeed.

Actually I don't really understand which CMake file should have the rpath linker options added. 
Is it gazebo ? The two loaded plugins ? or the libroslib.dylib and its friends ? Or should the 2 plugins be moved from catkin_ws/devel/lib/ to /opt/ros/indigo ?

**Comment by wjwwood** [comment]
> @wjwwood your fix would solve the problem for any package built using catkin ?

Yes, because anyone who would do `find_package(catkin ...)` would get those global CMake settings.

It sounds like the missing symbols in your gazebo plugin would be addressed by this because the libraries it is failing to find are built with catkin. If you're installing gazebo from Homebrew then they may be fixing the problem for gazebo. Homebrew will do a blanket rewrite of rpath's for libraries and executables on installation. See the functions in this file:

https://github.com/Homebrew/homebrew/blob/e15ae61bd0b317be5cd7e42af1dace0d18fbb28c/Library/Homebrew/keg_relocate.rb

You might have noticed `brew` invoking `install_name_tool` when pouring a bottle. I don't know for sure that is why the rest of gazebo works. They could also just have their RPATH on OS X setup correctly.

**Comment by wjwwood** [comment]
@dirk-thomas I opened a pr (https://github.com/ros/catkin/pull/784) with my draft suggestion. I don't think I'll have time to follow up on it for now, but maybe others can pick there and/or use it as a work around.

**Comment by dirk-thomas** [comment]
@wjwwood Great, thank you!

@LiohAu @kyonifer Can you please try the branch of the proposed PR and comment on it with your experience.

**Comment by LiohAu** [comment]
@dirk-thomas How do you test a modified catkin ? if it was any other ros package, I would build it with catkin_make in my local workspace, but I guess that it's a little bit more complicated for catkin itself ? :)

**Comment by wjwwood** [comment]
@LiohAu just put it in your workspace and then invoke it directly like this:

```
$ ./src/catkin/bin/catkin_make
```

**Comment by LiohAu** [comment]
@wjwwood I just tried it, and it did not solve my loading issue. Still getting this error message when roslaunching gazebo : 

```
[Err] [Plugin.hh:165] Failed to load plugin //Users/../catkin_ws/devel/lib/libgazebo_ros_paths_plugin.dylib: dlopen(//Users/../catkin_ws/devel/lib/libgazebo_ros_paths_plugin.dylib, 9): Library not loaded: libroslib.dylib
  Referenced from: //Users/../catkin_ws/devel/lib/libgazebo_ros_paths_plugin.dylib
  Reason: image not found
```

And here is the otool output : 

```
$ otool -L ~/catkin_ws/devel/lib/libgazebo_ros_paths_plugin.dylib 
/Users/.../catkin_ws/devel/lib/libgazebo_ros_paths_plugin.dylib:
    @rpath/libgazebo_ros_paths_plugin.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/gazebo6/lib/libgazebo.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_client.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_gui_building.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_gui_viewers.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_gui_model.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_gui.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_sensors.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_rendering.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_selection_buffer.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_physics_bullet.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_physics_simbody.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_physics_ode.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_physics.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_ode.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_transport.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_msgs.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_util.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_common.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_skyx.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_gimpact.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_opcode.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_opende_ou.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_math.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/gazebo6/lib/libgazebo_ccd.6.dylib (compatibility version 6.0.0, current version 6.5.1)
    /usr/local/opt/boost/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/boost/lib/libboost_signals-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/boost/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/boost/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/boost/lib/libboost_regex-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/boost/lib/libboost_iostreams-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/boost/lib/libboost_date_time-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/protobuf/lib/libprotobuf.9.dylib (compatibility version 10.0.0, current version 10.1.0)
    /usr/local/opt/sdformat3/lib/libsdformat.3.dylib (compatibility version 3.0.0, current version 3.6.0)
    /usr/local/opt/ignition-math2/lib/libignition-math2.2.dylib (compatibility version 2.0.0, current version 2.2.3)
    /usr/local/opt/ogre/lib/libOgreMain.1.7.4.dylib (compatibility version 0.0.0, current version 1.7.4)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
    libroslib.dylib (compatibility version 0.0.0, current version 0.0.0)
    libtf.dylib (compatibility version 0.0.0, current version 0.0.0)
    libtf2_ros.dylib (compatibility version 0.0.0, current version 0.0.0)
    libactionlib.dylib (compatibility version 0.0.0, current version 0.0.0)
    libmessage_filters.dylib (compatibility version 0.0.0, current version 0.0.0)
    libroscpp.dylib (compatibility version 0.0.0, current version 0.0.0)
    libxmlrpcpp.dylib (compatibility version 0.0.0, current version 0.0.0)
    libtf2.dylib (compatibility version 0.0.0, current version 0.0.0)
    librosconsole.dylib (compatibility version 0.0.0, current version 0.0.0)
    librosconsole_log4cxx.dylib (compatibility version 0.0.0, current version 0.0.0)
    librosconsole_backend_interface.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/log4cxx/lib/liblog4cxx.10.dylib (compatibility version 11.0.0, current version 11.0.0)
    libdynamic_reconfigure_config_init_mutex.dylib (compatibility version 0.0.0, current version 0.0.0)
    libroscpp_serialization.dylib (compatibility version 0.0.0, current version 0.0.0)
    librostime.dylib (compatibility version 0.0.0, current version 0.0.0)
    libcpp_common.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/console_bridge/lib/libconsole_bridge.0.2.dylib (compatibility version 0.2.0, current version 0.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

So now the rpath line is there, but that does not solve the issue. But maybe I misunderstood and it's the referenced libs (libroslib, libtf...) that I should have rebuilt instead of the libgazebo_ros_paths_plugin.dylib plugin ?

**Comment by wjwwood** [comment]
Everything that is in a catkin package must be rebuilt.

**Comment by LiohAu** [comment]
@wjwwood Ok, so basically it means that I cannot use homebrew package at all. I have to rebuild every ROS package from source (I thought rebuilding the packages in my own workspace was enough).

**Comment by wjwwood** [comment]
There aren't any homebrew packages other than gazebo and pcl and opencv. Which are not really considered part of the ROS. There aren't any homebrew packages for ros afaik.

**Comment by LiohAu** [comment]
So after reinstalling/recompiling everything, the dlopen() calls are not failing anymore because of libraries referenced by the library being loaded. 
Now it's the library loaded by dlopen() which is not found ^^
So basically it's this error : 
`[Err] [Plugin.hh:165] Failed to load plugin libgazebo_....dylib: dlopen(libgazebo_....dylib, 9): image not found
`

But if I use the full path in the plugin tag, it works. So like this (not really convenient when loading this on multiple PC) : 
`<plugin name="gazebo_ros_control" filename="/Users/../catkin_ws/devel/lib/libgazebo_ros_control.so">`

**Comment by wjwwood** [comment]
@LiohAu it sounds like gazebo might be expecting the given library to be on the `DYLD_LIBRARY_PATH`, which is no longer the case. That causes you to have to pass the absolute path instead. Not sure how to check that it true or to change it.

**Pull request closed without merging**
