### PR TITLE
only clean the test results of the current project

### PR DESCRIPTION
**Pull request by dirk-thomas**
Addresses #737.

@esteve @tfoote @wjwwood Please review.

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
I always thought that wiping the whole directory might be dangerous. Therefore I updated the clean commands to only remove files ending with `.xml`. So if someone passes in a "bad" test results dir it only wipes xml files and not everything.

**Comment by tfoote** [comment]
+1 that's safer

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
+1 again

**Pull request merged**
