### PR TITLE
documentation: updates for rostest

### PR DESCRIPTION
**Pull request by czalidis**
Modify documentation to reflect the new API for rostest, see ros/ros_comm#555.

### CODE REVIEW

**Comment by wjwwood** [comment]
I guess this patch would also apply to the "format1" version of this:

https://github.com/czalidis/catkin/blob/documentation_rostest/doc/howto/format1/rostest_configuration.rst

It's a little tedious to keep them in sync, but we should try to. Can you please update the "format1" version with your changes as well?

**Comment by wjwwood** [comment]
Otherwise it looks good, thanks @czalidis. +1

**Comment by czalidis** [comment]
Ok, I'll do. I completely forgot about "format1"...

**Comment by dirk-thomas** [comment]
Can you please add a newlines before the start of a new sentence (in the paragraphs you added)?

**Comment by czalidis** [comment]
You mean that each sentence should start in a new line? (because thats not the case for the rest of the document)

**Comment by dirk-thomas** [comment]
Yes, this is currently our recommended style since it makes diffs easier to read.
Otherwise changes can propagate through the whole paragraph due to re-wrapping everything.

Don't worry about the existing paragraph - they need to be cleaned up at some point.

**Comment by dirk-thomas** [comment]
Thanks!

**Pull request merged**
