### PR TITLE
catkin_make_isolated to accepd -D options

### PR DESCRIPTION
**Pull request by wjwwood**
catkin_make accepts -d options to pass to cmake. It seems catkin_make_isolated does not:

```
$ src/catkin/bin/catkin_make_isolated -DFOO=3
catkin_make_isolated: error: unrecognized arguments: -DFOO=3
```

### CODE REVIEW

**Comment by cottsay** [comment]
This is a blocker for Fedora. I've seen another issue posted in which someone commented on this issue, but they were told to use catkin_make instead, as it accepts CMake options. However, this will only work when building the ros_comm variant, as desktop and desktop-full have packages like opencv2 or pcl which are plain cmake packages and require catkin_make_isolated.

Particularly, Fedora NEEDS "-DSETUPTOOLS_DEB_LAYOUT=OFF" for the "--install" option to work.

**Comment by wjwwood** [comment]
@dirk-thomas for review

**Pull request merged**
