### PR TITLE
fix rollback of environment when workspace has been deleted

### PR DESCRIPTION
**Pull request by dirk-thomas**
@jbohren Please verify that this patch address the issue you were able to reproduce in https://github.com/catkin/catkin_tools/issues/47#issuecomment-44228618

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by jbohren** [comment]
Testing this now.

**Comment by jbohren** [comment]
What is the easiest way to test this without uninstalling catkin?

**Comment by dirk-thomas** [comment]
Just clone catkin into a workspace and build that ontop of what is already installed. It will overlay the installed version of catkin.

Then you can use the same sequence ontop which you used to reproduce the problem.

**Comment by jbohren** [comment]
Yeah it looks like this fixes it!

**Comment by jbohren** [comment]
+1 good to merge

**Pull request merged**
