### PR TITLE
refactored and unit-test parse_package_xml.py

### PR DESCRIPTION
**Pull request by tkruse**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I merged the changes and fixed the usage of the Mock() constructor (see related commit). Please use that initialization for mocks for future patches.

**Comment by tkruse** [comment]
Sorry, did the usage of the Mock() contructor with arguments not work for
you, or what is the problem with it?

**Comment by dirk-thomas** [comment]
The mock constructor does not support kwargs - at least not in the version shipped with precise. I fixed that already for another pull request recently (can't find which one).

**Comment by tkruse** [comment]
Ok, I am on oneiric, and it works, that's weird. Sorry about it, if i see
it again I will fix it.

**Comment by tkruse** [comment]
I want to find out what happens. Can you run this please:

> > > import mock
> > > mock.**version**
> > > '1.0b1'

**Comment by dirk-thomas** [comment]
Precise ships with mock version 0.7.2
http://packages.ubuntu.com/precise/python-mock

**Pull request merged**
