### PR TITLE
Convert windows path to cmake path

### PR DESCRIPTION
**Pull request by stonier**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Can you mention in which use case this was an issue?

**Comment by stonier** [comment]
It failed topological ordering as soon as it hit the ros stack. Incoming path strings looked like "ros\core\mk" which would cause CMake to abort.

**Comment by stonier** [comment]
This was something that got lost in fuerte -> groovy. You can see we had it implemented in

https://github.com/ros/catkin/blob/832c1312cccc79ac7325bfe13dc22b87a5389a93/cmake/em/topologically_traverse.cmake.em

**Comment by dirk-thomas** [comment]
Weird. Actually the topological order worked fine for me yesterday on Windows. I will look into that soonish.

**Comment by stonier** [comment]
Closing this and re-opening from the pull request from my fork.

**Pull request closed without merging**
