### PR TITLE
update package manifest to format 2

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by tfoote** [comment]
It needs a run_depend on at least python since it has python scripts for use at runtime.

**Comment by dirk-thomas** [comment]
`python` would be a `depend` since it is required for build time as well as run time. But we don't list `python` in any other ROS package which contains Python scripts so I am not convinced with this PR.

**Comment by wjwwood** [comment]
`catkin_pkg` implicitly brings in the dependency on `Python`, but I don't think it would be wrong for `catkin` to depend on it, but if we want to be consistent with existing packages, then I wouldn't add it.

**Comment by tfoote** [comment]
yeah, i guess it is in our prerequisites list and is implicitly dependend upon. +1

**Comment by dirk-thomas** [comment]
We currently also don't have a `python` rosdep entry - only one for the dev package which is not really required for catkin. I will leave it out for now (as it is for all other packages).

**Pull request merged**
