### PR TITLE
suggest what to do when CATKIN_NONHOMOGENEOUS_WORKSPACE

### PR DESCRIPTION
**Pull request by k-okada**
this has been asked several times and answers is try catkin_make_isolated

http://answers.ros.org/question/66696/error-with-catkin_make-when-building-package-beginner_tutorials/
http://answers.ros.org/question/66169/pcl-17-install-on-groovy/

### CODE REVIEW

**Comment by jbohren** [comment]
@k-okada it's currently in beta, but I'd suggest trying the new top-level build tool from the catkin_tools package: http://catkin-tools.readthedocs.org/en/latest/

This tool can build catkin and cmake packages simultaneously in the same workspace and can do this in parallel.

Also there are a bunch of additional features in my branch which are still pending review: 

http://jbohren-ct.readthedocs.org/en/metadata-file/index.html
https://github.com/jbohren-forks/catkin_tools

**Comment by k-okada** [comment]
@jbohren thanks for info, I'm aware of that, because dave colman was here until last month and he always show me how your tools are excellent. Do you have plan to release that package as deb or pip? This is my fault, but I have psychological barrier to install new tools from source.

**Comment by jbohren** [comment]
> thanks for info, I'm aware of that, because dave colman was here until last month and he always show me how your tools are excellent. Do you have plan to release that package as deb or pip? This is my fault, but I have psychological barrier to install new tools from source.

Well it will definitely be released after my pull request ( https://github.com/catkin/catkin_tools/pull/80 ) is merged, but that's still pending review by @wjwwood. That probably won't happen until after ROSCon.

**Comment by wjwwood** [comment]
We aren't going to suggest catkin_tools over cmi until several things are fixed in catkin_tools, see:
- https://github.com/ros/catkin/issues/611
- https://github.com/catkin/catkin_tools/issues/90

> Do you have plan to release that package as deb or pip? 

It has already been released once, via apt-get get it is `python-catkintools` (this will be fixed to be `python-catkin-tools` in the next release) and via pip it is `catkin_tools`.

As the original issue, I think it would be a good hint to have in the error message, please consider a pull request:

https://github.com/ros/catkin/blob/indigo-devel/cmake/catkin_workspace.cmake#L88

As @jbohren pointed out, until after ROSCon (this week) we will probably be booked solid.

**Comment by dirk-thomas** [comment]
Thank you, merged (with slight modification) in c58b1d7f16beaa279d9ae4ab019a2c34ad70c63e.

**Comment by k-okada** [comment]
thank you for merging and correct English ;-), 
Try "the" XYZ  "instead". I'll use this expression next time.

**Comment by k-okada** [comment]
I just want to say catkin_tools is great, thanks!!!  @jbohren :star::star::star::star::star:

**Pull request closed without merging**
