### PR TITLE
add support for GMock

### PR DESCRIPTION
**Pull request by dirk-thomas**
Builds on top of #896 and addresses some issues.

@v-lopez FYI

### CODE REVIEW

**Comment by v-lopez** [comment]
@dirk-thomas Thanks for the changes, lgtm.

**Comment by dirk-thomas** [comment]
@mikepurvis Would it be possible for you to use this branch for your testing for a little while? That would give us more confidence that it doesn't introduce any regressions...

**Comment by mikepurvis** [comment]
I've switched our distribution to this branch. FYI @tspicer01

**Comment by mikepurvis** [comment]
We're not actively using the new gmock support, but I believe none of our unittests have gone up in flames as a result of this change.

**Comment by dirk-thomas** [comment]
@v-lopez Thank you for providing this. I will go ahead and merge this so it will be part of the next release of this package.

**Comment by dirk-thomas** [comment]
What I didn't realize when review this is that the patch duplicates large blocks of the logic and copy-n-pastes it into the new function `catkin_find_gmock_source`. In light of this patch failing to build for melodic (which has the `googletest` 1.8.0) (https://github.com/ros/catkin/issues/910#issuecomment-359968542) this should not only be fixed but also be cleaned up.

**Pull request merged**
