### PR TITLE
Fix interface targets that do not have libraries

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
This is to address issue #1006

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
It looks travis passed on 2.7 but for 3.4 it was unable to download something it required.

**Comment by dirk-thomas** [comment]
@Levi-Armstrong Please rebase your branch against the latest state of the target branch in order to pass CI.

**Comment by Levi-Armstrong** [comment]
@dirk-thomas I just rebased the branch.

**Comment by dirk-thomas** [comment]
Thanks for the patch.

Please use the following phrase in the future when referencing the issue a PR addresses since it will make sure the ticket gets closed automatically when the PR is merged:

> Fixes #1006

**Pull request merged**
