### PR TITLE
work around travis using non-debian Python by default

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by wjwwood** [comment]
I think this one is related: https://code.google.com/p/python-nose/issues/detail?id=481

**Comment by wjwwood** [comment]
Well that is a workaround I guess, did you open a ticket against travis? Should you link to it from here?

**Comment by dirk-thomas** [comment]
This is at least a workaround until #626 gets implemented.

**Comment by dirk-thomas** [comment]
Travis won't change it - they will use clean upstream Python from now on - see other ticet for reference.

**Pull request merged**
